#!/usr/bin/env bash

set -euo pipefail

# Helper script to enable the performance governor with proton or others
if ! command -v tlpctl &>/dev/null; then
    echo "Error: tlpctl not found" >&2
    exit 1
fi

# Don't fail if the CPU driver doesn't support performance power profile
if ! tlpctl list | grep -q 'performance:'; then
    exec "$@"
fi

# Set performance governors, as long the game is launched
if [ -n "${GAME_PERFORMANCE_SCREENSAVER_ON:-}" ]; then
    exec tlpctl launch -p performance \
        -r "Launched with CachyOS tlp-game-performance utility" -- "$@"
else
    exec systemd-inhibit --why "CachyOS tlp-game-performance is running" tlpctl launch -p \
        performance -r "Launched with CachyOS tlp-game-performance utility" -- "$@"
fi
